name: Release

on:
  release:
    types: [published]
  #push:
  #  tags: "[1-9]+.[0-9]+.[0-9]+"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: coursier/cache-action@90c37294538be80a558fd665531fcdc2b467b475 # v8.1.0
        with:
          extraKey: ${{ runner.os }}
      - uses: coursier/setup-action@fd1707a76b027efdfb66ca79318b4d29b72e5a02 # v3.0.0
        with:
          jvm: adopt:1.8
      # uses sbt-github-packages, see build.sbt
      - name: Publish with SBT
        run: bin/sbt publish
      - name: Publish with SBT
        run: bin/sbt publish -DsparkVersion=3.5.1
